[package]
name = "color-regex"
version = "0.1.0"
authors = ["Benjamin Fry <benjamin.fry@salesforce.com>"]
description = "Uses https://docs.rs/regex to match and colorize log lines"

[[bin]]
name = "crx"
path = "src/bin.rs"

[dependencies]
clap = "2.25.0"
colored = "1.5.2"
regex = "0.2"
